language: node_js

node_js:
  - "0.12"

before_install:
  - node --version
  - npm --version

before_script:
  - npm install -g gulp
  - sleep 3
  - npm install
  - cd e2e/step-definitions/api

script:
 - gulp api

notifications:
  email:
    - paul@jaffamonkey.com
