language: node_js

node_js:
  - "0.10"

before_install:
  - node --version
  - npm --version

before_script:
  - npm install -g gulp
  - sleep 3
  - sudo npm install
  - cd e2e/step-definitions/api
  - sudo ln -s node_modules/apickli/apickli-gherkin.js apickli-gherkin.js

script:
 - gulp api

notifications:
  email:
    - paullittlebury@gmail.com
