language: node_js

node_js:
  - "0.12"

before_install:
  - node --version
  - npm --version

before_script:
  - npm install -g gulp
  - sleep 3

script:
 - npm install
 - sudo ln -s node_modules/apickli/apickli-gherkin.js e2e/step-definitions/api/apickli-gherkin.js
 - gulp api

notifications:
  email:
    - paullittlebury@gmail.com
