language: node_js

node_js:
  - "0.11"

before_install:
  - node --version
  - npm --version

before_script:
  - npm install -g gulp
  - sleep 5

script:
 - npm install
 - ln -s e2e/step-definitions/api/apickli-gherkin.js node_modules/apickli/apickli-gherkin.js
 - gulp api

notifications:
  email:
    - paullittlebury@gmail.com
