language: node_js

node_js:
  - "0.12"

before_install:
  - node --version
  - npm --version

before_script:
  - npm install
  - npm install -g gulp
  - npm install -g phantomjs
  - "wget http://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.jar"
  - "DISPLAY=:10 xvfb-run java -jar selenium-server-standalone-2.47.1.jar > /dev/null &"
  - sleep 5

script:
 - gulp jenkins

matrix:
  allow_failures:
    - node_js: "0.8"
    - node_js: "0.6"

notifications:
  email:
    - paullittlebury@gmail.com
