language: node_js

node_js:
  - "0.12"

before_install:
  - node --version
  - npm --version

before_script:
  - sleep 3
  - npm install
  - ln -s node_modules/apickli/apickli-gherkin.js e2e/step-definitions/api/apickli-gherkin.js

script:
  - node_modules/protractor/bin/protractor api.conf.js

notifications:
  email:
  - paullittlebury@gmail.com
